DROP TABLE IF EXISTS users,
posts,
comments;
CREATE TABLE users (
  user_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL,
  password_hash TEXT NOT NULL
);
CREATE TABLE posts (
  post_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  caption TEXT NOT NULL,
  photo_url TEXT NOT NULL,
  tags TEXT [] NOT NULL
);
CREATE TABLE comments (
  comment_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  comment_by TEXT NOT NULL,
  post_id BIGINT NOT NULL,
  comment TEXT NOT NULL
);